### ISSUE TITLE
Using the official standalone version of comfyui saves the weight file in the wrong place.

### ISSUE THREAD

**Issue by whmc76** [daniabib/ComfyUI_ProPainter_Nodes#5]
![image](https://github.com/daniabib/ComfyUI_ProPainter_Nodes/assets/129386342/f4ef860e-e3c7-4bd1-9d39-1649abe86986)

E:\VIDEO\ComfyUI_video\custom_nodes\ComfyUI_ProPainter_Nodes\weights

and it should be

E:\VIDEO\ComfyUI_video\ComfyUI\custom_nodes\ComfyUI_ProPainter_Nodes

**Comment by daniabib** [comment]
Hi! Thanks for sharing this. 
I will create a pull request to fix how the node handles file download and it should fix the problem.
Let me know if it persists.
