### ISSUE TITLE
How to create an outpainting workflow?

### ISSUE THREAD

**Issue by spartakus-santiago** [daniabib/ComfyUI_ProPainter_Nodes#7]
Hello! I am trying to use ProPainter to change the aspect ratio of a square video, to make it 16:9 (horizontal).
But all I can find on internet are tutorials about the inpainting process, not the outpainting.
Do you know how can I do that? Some can help me with some tutorial or instruction, some workflow model for example?

**Comment by daniabib** [comment]
Hi! The outpainting was not properly implemented in the original ProPainter repo. It has an option for OP that outputs a padded image filled with the model results, but it is basically noise. I didn't have the time to dig into it to see if I could find a solution but I decided to implement the node if someone wants to experiment with it.

[propainter-outpainting-workflow.json](https://github.com/user-attachments/files/16335722/propainter-outpainting-workflow.json)

Resulting video with noisy expanded width:
https://github.com/user-attachments/assets/24f6e629-1e10-4c65-aa34-1130d8f6011c
