### ISSUE TITLE
How to generate the mask video?

### ISSUE THREAD

**Issue by tiptinker** [daniabib/ComfyUI_ProPainter_Nodes#8]
![image](https://github.com/user-attachments/assets/442b649e-7b6f-4352-a0de-e87153b3ff03)

Is there another workflow for generating mask video?

**Comment by daniabib** [comment]
You will need other nodes to create masks in ComfyUI.

I use external sources for masking as the YoloSAM node is not the best option for videos, but it works for simple cases:
https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM

Meta just released SAM-2 which seems to support video. It is very likely that someone will build a node for it soon.

**Comment by tiptinker** [comment]
I sucessfully removed the girl dancing on the stage.
![image](https://github.com/user-attachments/assets/8326a17d-9465-4820-966e-f6897e9d9073)

While I need more, like making her dress another clothes, is there another workflow allowing text prompt input for actual inpainting? current workflow is more like a remove object workflow.

**Comment by daniabib** [comment]
ProPainter isn't a latent model nor text-to-image, so it can't hallucinate following a prompt. It is for object removal and video completion only. I don't know any specific workflow for "actual" (object removal is inpainting also, haha) video inpainting yet.

**Comment by digilateraldev** [comment]
send the workflow @pandayummy
